server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app
    username: root
    password: Jeet@3558
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: debug

  #JPA and Hibernate configuration
#  spring:

# this properties are imp for production in company
#    hikari :
#      pool-name: HikariCP
#      maximum-pool-size: 5
#      connection-timeout: 10000
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      validation-timeout: 5000
#      leak-detection-threshold: 20000
#      initialization-fail-timeout: 5000






